#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

# ---------
# variables

TODAY=`eval date +%Y%m%d%H%M%S`
WORKPATH=${1-"/var/www/html/themes/novaoptic"}

# ------ 
echo "Running npm install"
cd $WORKPATH
npm install

echo "Running gulp production"

cd $WORKPATH
gulp build --production

echo "Done, enjoy!"
