#!/usr/bin/perl -w
# -*- perl -*-
# vim: ft=perl
#
# Copyright (C) 2013 Cristian Spoiala
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#
# Plugin to fetch total power consumption from the IBM Blade Center SNMP agent 
#

use strict;

use Net::SNMP qw(oid_lex_sort);
use Munin::Plugin::SNMP;

# The OIDs for total power
my $oid_power_limit = '1.3.6.1.4.1.2.3.51.2.2.10.5.1.1.0';
my $oid_power_used = '1.3.6.1.4.1.2.3.51.2.2.10.5.1.2.0';

my $session = Munin::Plugin::SNMP->session(-translate =>
                                           [ -timeticks => 0x0 ]);

my $power_limit = $session->get_single ($oid_power_limit) || 'U';
my $power_used = $session->get_single ($oid_power_used) || 'U';

my $unit = chop($power_limit);
my $unit2 = chop($power_used);

if (defined $ARGV[0] and $ARGV[0] eq "config")
{
    print "host_name monitoring\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_vlabel Watts\n";
    print "graph_title Blade Center Total Power Consumption Detailed\n";
    print "graph_category blade_center\n";
    print "graph_info This graph shows power consumption.\n";   

    print "power_limit.label power_limit\n";
    print "power_limit.draw AREA\n";
    print "power_limit.info Blade Center Power Limit\n";

    print "power_used.label power_used\n";
    print "power_used.draw AREA\n";
    print "power_used.info Blade Center Power Used\n";

    exit 0;
}
print "power_limit.value ", $power_limit, "\n";
print "power_used.value ", $power_used, "\n";



